version: '3.8'

services:
  app:
    image: ghcr.io/instrument-data-source/instrument-quote-data-source-srv
    restart: always
    ports:
      - 30100:80
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
 
volumes:
  instrument-quote-data-source-srv-postgres-data:
    external: true
