name: Project Unit tests

on:
  push:
    branches: [ workflow ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/devcontainers/dotnet:0-7.0
    
    services:
      db:
        image: postgres:14.3
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: 
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 3

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run tests
        run: dotnet test ./Instrument.Quote.Source.Srv.sln --configuration Release
