name: Build and Push Docker Image

on:
  release:
    types: released

env:
  IMAGE_NAME: ghcr.io/instrument-data-source/instrument-quote-data-source-srv/instrument-quote-data-source-srv

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_PUSH_TOKEN }}
      
      - name: GITHUB_REF
        run: echo $GITHUB_REF

      - name: Build image
        run: docker buildx build --platform linux/amd64 -t $IMAGE_NAME:$GITHUB_REF .
      
      - name: Push image
        run: docker push $IMAGE_NAME:$GITHUB_REF