name: Build and Push Docker Image

on:
  release:
    types: released

env:
  IMAGE_NAME: ghcr.io/instrument-data-source/instrument-quote-data-source-srv

jobs:
  testing:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:7.0

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Run tests
        run: dotnet test ./Instrument.Quote.Source.Srv.sln --configuration Release --verbosity m --no-restore

  build:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Print Image Name
        run: echo $IMAGE_NAME
      
      - name: Retrieve release version
        id: release_info
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Display release version
        run: echo $RELEASE_VERSION
      
      - name: TagName
        run: echo "DOCKER_IMAGE_NAME_WITH_TAG=$(echo ${IMAGE_NAME}:${RELEASE_VERSION} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Display TagName
        run: echo $DOCKER_IMAGE_NAME_WITH_TAG
    
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${IMAGE_NAME}:${RELEASE_VERSION}
            ${IMAGE_NAME}:latest