name: Test WF

on:
  push:
    branches: [ workflow ]

env:
  IMAGE_NAME: ghcr.io/instrument-data-source/instrument-quote-data-source-srv

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Image Name
        run: echo $IMAGE_NAME

      - name: Retrieve release version
        id: release_info
        run: echo "RELEASE_VERSION=v0.1" >> $GITHUB_ENV

      - name: Display release version
        run: echo $RELEASE_VERSION
      
      - name: Display release version aly
        run: echo ${{ env.RELEASE_VERSION }}

      - name: Build and Publish head Docker image
        uses: VaultVulp/gp-docker-action@1.1.12
        with:
            github-token: ${{ secrets.PACKAGE_PUSH_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
            image-name: $IMAGE_NAME
            